/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  Permissions,
  PermissionsInterface,
} from "../../../../contracts/SbCoreDAO/contracts/Permissions";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "granter",
        type: "address",
      },
      {
        internalType: "address",
        name: "grantee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "permission",
        type: "uint256",
      },
    ],
    name: "__hasPermission",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum Permissions.Permission",
        name: "p",
        type: "uint8",
      },
    ],
    name: "getPermissionCode",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "permissions",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101ff806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80631f9838b514610046578063a572dc7414610081578063c9eb7b1b14610094575b600080fd5b61006e61005436600461011c565b600060208181529281526040808220909352908152205481565b6040519081526020015b60405180910390f35b61006e61008f36600461014f565b6100e0565b6100d06100a2366004610177565b6001600160a01b03928316600090815260208181526040808320949095168252929092529190205416151590565b6040519015158152602001610078565b6000808260028111156100f5576100f56101b3565b6001901b9392505050565b80356001600160a01b038116811461011757600080fd5b919050565b6000806040838503121561012f57600080fd5b61013883610100565b915061014660208401610100565b90509250929050565b60006020828403121561016157600080fd5b81356003811061017057600080fd5b9392505050565b60008060006060848603121561018c57600080fd5b61019584610100565b92506101a360208501610100565b9150604084013590509250925092565b634e487b7160e01b600052602160045260246000fdfea264697066735822122058a11d9b33fbfd8877d948b9154cf52812b08cb7183161356e4796f6365b0c3064736f6c63430008110033";

type PermissionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PermissionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Permissions__factory extends ContractFactory {
  constructor(...args: PermissionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Permissions> {
    return super.deploy(overrides || {}) as Promise<Permissions>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Permissions {
    return super.attach(address) as Permissions;
  }
  override connect(signer: Signer): Permissions__factory {
    return super.connect(signer) as Permissions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PermissionsInterface {
    return new utils.Interface(_abi) as PermissionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Permissions {
    return new Contract(address, _abi, signerOrProvider) as Permissions;
  }
}
