/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as legacyOracleAdapterV3Sol from "./LegacyOracleAdapterV3.sol";
export type { legacyOracleAdapterV3Sol };
