/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISbEvents,
  ISbEventsInterface,
} from "../../../../contracts/Switchboard/interfaces/ISbEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "AggregatorAccountInit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "aggregatorAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "funder",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "AggregatorFundEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "aggregatorAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "intervalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "balanceLeftForInterval",
        type: "uint256",
      },
    ],
    name: "AggregatorIntervalRefreshed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "aggregatorAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "varianceThreshold",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minJobResults",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "forceReportPeriod",
        type: "uint256",
      },
    ],
    name: "AggregatorResponseSettingsUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "aggregatorAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oracle",
        type: "address",
      },
      {
        indexed: true,
        internalType: "int256",
        name: "value",
        type: "int256",
      },
    ],
    name: "AggregatorSaveResult",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "aggregatorAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "int256",
        name: "value",
        type: "int256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "AggregatorUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "OracleAccountInit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oracleAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "aggregatorAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "OraclePayoutEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "OracleQueueAccountInit",
    type: "event",
  },
] as const;

export class ISbEvents__factory {
  static readonly abi = _abi;
  static createInterface(): ISbEventsInterface {
    return new utils.Interface(_abi) as ISbEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISbEvents {
    return new Contract(address, _abi, signerOrProvider) as ISbEvents;
  }
}
