/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iLegacyOracleSol from "./ILegacyOracle.sol";
export type { iLegacyOracleSol };
export type { ISwitchboard } from "./ISwitchboard";
export type { LegacyOracleAdapter } from "./LegacyOracleAdapter";
export type { Switchboard } from "./Switchboard";
export type { SwitchboardV2TEST } from "./SwitchboardV2TEST";
