/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as switchboardV2TestTSol from "./SwitchboardV2TEST.t.sol";
export type { switchboardV2TestTSol };
