/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type { EventLib, EventLibInterface } from "../../../src/event/EventLib";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "adapter",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "NewAdapter",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "value",
        type: "int256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "NewResult",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "feedId",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "value",
        type: "int256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ReadEvent",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122035b3c83b596aaa8a553f5b063be3db2964a35c3a222cc18eb29c1e8a65e1522964736f6c63430008110033";

type EventLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EventLib__factory extends ContractFactory {
  constructor(...args: EventLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<EventLib> {
    return super.deploy(overrides || {}) as Promise<EventLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EventLib {
    return super.attach(address) as EventLib;
  }
  override connect(signer: Signer): EventLib__factory {
    return super.connect(signer) as EventLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventLibInterface {
    return new utils.Interface(_abi) as EventLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventLib {
    return new Contract(address, _abi, signerOrProvider) as EventLib;
  }
}
