/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as legacyOracleAdapterSol from "./LegacyOracleAdapter.sol";
export type { legacyOracleAdapterSol };
import type * as switchboardSol from "./Switchboard.sol";
export type { switchboardSol };
import type * as switchboardAttestationServiceSol from "./SwitchboardAttestationService.sol";
export type { switchboardAttestationServiceSol };
import type * as switchboardV3Sol from "./SwitchboardV3.sol";
export type { switchboardV3Sol };
import type * as contracts from "./contracts";
export type { contracts };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
import type * as test from "./test";
export type { test };
