/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISwitchboard,
  ISwitchboardInterface,
} from "../../../../src/util/Recipient.sol/ISwitchboard";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "functionId",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "callFunction",
    outputs: [
      {
        internalType: "address",
        name: "callId",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISwitchboard__factory {
  static readonly abi = _abi;
  static createInterface(): ISwitchboardInterface {
    return new utils.Interface(_abi) as ISwitchboardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwitchboard {
    return new Contract(address, _abi, signerOrProvider) as ISwitchboard;
  }
}
