/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iLegacyOracleSol from "./ILegacyOracle.sol";
export type { iLegacyOracleSol };
import type * as readSol from "./read.sol";
export type { readSol };
export type { ISwitchboard } from "./ISwitchboard";
export * as factories from "./factories";
export type { AggregatorV3Interface } from "./ILegacyOracle.sol/AggregatorV3Interface";
export { AggregatorV3Interface__factory } from "./factories/ILegacyOracle.sol/AggregatorV3Interface__factory";
export { ISwitchboard__factory } from "./factories/ISwitchboard__factory";
export type { ReadAFeed } from "./read.sol/ReadAFeed";
export { ReadAFeed__factory } from "./factories/read.sol/ReadAFeed__factory";
