/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as receiver from "./Receiver";
export type { receiver };
import type * as admin from "./admin";
export type { admin };
import type * as eip2535 from "./eip2535";
export type { eip2535 };
import type * as error from "./error";
export type { error };
import type * as event from "./event";
export type { event };
import type * as util from "./util";
export type { util };
export type { SwitchboardPushReceiver } from "./SwitchboardPushReceiver";
