/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iLegacyOracleSol from "./ILegacyOracle.sol";
export type { iLegacyOracleSol };
export type { IAttestationServiceEvents } from "./IAttestationServiceEvents";
export type { ISwitchboard } from "./ISwitchboard";
export type { ISwitchboardAttestationService } from "./ISwitchboardAttestationService";
export type { ISwitchboardEvents } from "./ISwitchboardEvents";
